import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const links = [{
    label: "home",
    route: "/"
  } ,{
    label: "proyectos",
    route: "/proyectos" 
  }
  ]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <nav>
        <ul>
          {links.map(({label, route}) =>(
            <li key={route}>
              <Link href={route}>
                {label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </html>
  )
}
